
import { Customer } from './types';

export const initialCustomers: Customer[] = [
  { id: "1", name: "KLEITON ANDRE DO NASCIMENTO DE LIMA", address: "RUA MANOEL CLODOALDO DA SILVA, 24", neighborhood: "ANA CATARINA", city: "CANGUARETAMA", state: "RN", phone: ["(84)99171-5497"], secondaryAddresses: [] },
  { id: "2", name: "TAIANE CIPRIANA DA COSTA", address: "RUA LAGOA DE MARACAJAÚ, 85 B", neighborhood: "CENTRO", city: "EXTREMOZ", state: "RN", phone: ["(84)99915-2819"], secondaryAddresses: [] },
  { id: "3", name: "BRUNA LUANA DE OLIVEIRA PEREIRA", address: "RUA PRINCIPAL , 151 COMERCIAL", neighborhood: "CENTRO", city: "EXTREMOZ", state: "RN", phone: ["981677177"], secondaryAddresses: [] },
  { id: "4", name: "LUANA KAROLAYNE DA SILVA CARDOSO", address: "RUA SHALOM, 14 SALA 7", neighborhood: "CENTRO", city: "EXTREMOZ", state: "RN", phone: ["981225010"], secondaryAddresses: [] },
  { id: "5", name: "CRISTIANY ANDRADE NUNES CLAUDINO ALVES", address: "RUA SAO MIGUEL, 10", neighborhood: "COSTA DAS", city: "EXTREMOZ", state: "RN", phone: ["986283264"], secondaryAddresses: [] },
  { id: "6", name: "SUMAIA DE OLIVEIRA SILVA", address: "RUA RUA ANDORRA, 28 CONJ 40", neighborhood: "JARDINS DE", city: "EXTREMOZ", state: "RN", phone: ["981609447"], secondaryAddresses: [] },
  { id: "7", name: "MARIA CLEONICE DOS SANTOS ALVES TIBAO", address: "RUA JANUÁRIO COCO, 106", neighborhood: "MOINHO DOS VENTOS", city: "EXTREMOZ", state: "RN", phone: ["987000650"], secondaryAddresses: [] },
  { id: "8", name: "LUCIENE MARIA DO NASCIMENTO", address: "RUA NISIA FLORESTA, 104", neighborhood: "MOINHO DOS VENTOS", city: "EXTREMOZ", state: "RN", phone: ["988811664"], secondaryAddresses: [] },
  { id: "9", name: "MARIA LUCIA GALVAO DO NASCIMENTO", address: "RUA COR MANOEL DUARTE, 64 CS GRANDE", neighborhood: "CENTRO", city: "GOIANINHA", state: "RN", phone: ["991082850"], secondaryAddresses: [] },
  { id: "10", name: "ANDREIA ANDRADE DE LIMA", address: "RUA JOÃO PRIMENIO B SIMONETE, 23", neighborhood: "CENTRO", city: "GOIANINHA", state: "RN", phone: ["9 9959-4487"], secondaryAddresses: [] },
  { id: "11", name: "ARTHUR HENRIQUE DA CRUZ", address: "RUA INALDO BARALHO, 152", neighborhood: "MATADOURO NOVO", city: "GOIANINHA", state: "RN", phone: ["84991524091"], secondaryAddresses: [] },
  { id: "12", name: "LUIS JOSE DE MORAIS", address: "RUA SEVERINO BARROS, 137 PQ DOS", neighborhood: "BELA VISTA", city: "MACAIBA", state: "RN", phone: ["999266393"], secondaryAddresses: [] },
  { id: "13", name: "VALDECK FLORENCIO DE SOUZA", address: "RUA DIX SEPT ROSADO, 16", neighborhood: "CENTRO", city: "MACAIBA", state: "RN", phone: ["91046327"], secondaryAddresses: [] },
  { id: "14", name: "KARINA RAYNE DA SILVA 05830465418", address: "RUA DR FRANCISCO DA CRUZ, 83", neighborhood: "CENTRO", city: "MACAIBA", state: "RN", phone: ["991348030"], secondaryAddresses: [] },
  { id: "15", name: "FLÁVIA", address: "RUA ROSA FILOMENA , 237", neighborhood: "CIDADE DAS ROSAS", city: "NATAL", state: "RN", phone: ["988412377"], secondaryAddresses: [] },
  { id: "16", name: "JOSIMARY DANTAS DE MEDEIROS", address: "RUA MARIA QUITÉRIA, 14C", neighborhood: "EMAUS", city: "NATAL", state: "RN", phone: ["84 991814427"], secondaryAddresses: [] },
  { id: "17", name: "LUCIANA (EMAÚS)", address: "RUA NOSSA SENHORA DA APRESENTAÇÃO, 115", neighborhood: "EMAÚS", city: "NATAL", state: "RN", phone: [], secondaryAddresses: [] },
  { id: "18", name: "MARIA DAS GRAÇAS FERNANDES", address: "RUA RIO LARGO, 47", neighborhood: "EMAÚS", city: "NATAL", state: "RN", phone: ["84 987589293"], secondaryAddresses: [] },
  { id: "19", name: "MARIA FERNANDA COSTA", address: "RUA CRISANTEMO , 6 SALAO", neighborhood: "JARDIM", city: "NATAL", state: "RN", phone: ["996674613"], secondaryAddresses: [] },
  { id: "20", name: "AMANDA CRISTIANE SILVA DA ROCHA", address: "AVENIDA BUMBA MEU BOI, 850 C", neighborhood: "LAGOA AZUL", city: "NATAL", state: "RN", phone: ["988724023"], secondaryAddresses: [] },
  { id: "21", name: "JOELMA DO NASCIMENTO SOARES DA COSTA", address: "AVENIDA POETA RENATO CALDAS, 620 L. BOA", neighborhood: "LAGOA AZUL", city: "NATAL", state: "RN", phone: ["988972530"], secondaryAddresses: [] },
  { id: "22", name: "ERICA JANAINA DE OLIVEIRA TARGINO", address: "RUA BELA VISTA, 531 A LOJA 02", neighborhood: "LAGOA AZUL", city: "NATAL", state: "RN", phone: ["992346083"], secondaryAddresses: [] },
  { id: "23", name: "LUIZA (LENINGRADO)", address: "RUA JOSÉ VICENTE, 1900", neighborhood: "LENINGRADO", city: "NATAL", state: "RN", phone: ["996935152"], secondaryAddresses: [] },
  { id: "24", name: "ELISANDRA MEDEIROS DO NASCIMENTO", address: "AVENIDA DOUTOR JOAO MEDEIROS FILHO", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["88588798"], secondaryAddresses: [] },
  { id: "25", name: "WILLIANE INGRID FERREIRA DE LIMA", address: "AVENIDA GOV ANTONIO DE M E SOUZA , 984", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["91592559"], secondaryAddresses: [] },
  { id: "26", name: "PAULA ANDREZA DO NASCIMENTO SILVA", address: "AVENIDA MAR DO NORTE, 23", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["99328105"], secondaryAddresses: [] },
  { id: "27", name: "MARINES SOARES DA SILVA", address: "AVENIDA MOEMA TINOCO DA CUNHA LIMA", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["99974-0107"], secondaryAddresses: [] },
  { id: "28", name: "ANA LIGIA SALVIANO SILVA DE SOUZA", address: "RUA ALCIONE DOWSLEY (LOT SIT FLORE, 135", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["32069682"], secondaryAddresses: [] },
  { id: "29", name: "CLAUDIANA SOARES CANDIDO ARAUJO", address: "RUA CASTELO BRANCO , 532 A", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["999541701"], secondaryAddresses: [] },
  { id: "30", name: "ELIADA DOS SANTOS SILVA", address: "RUA DOS TRES PODERES, 89 C", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["998971224"], secondaryAddresses: [] },
  { id: "31", name: "TAYNARA DA SILVA TAVEIRA", address: "RUA DOUTOR CARNEIRO RIBEIRO, 313 LOT", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["986324762"], secondaryAddresses: [] },
  { id: "32", name: "MARIA DAS VITORIAS DE SOUZA", address: "RUA ESCRITOR GILBERTO AMADO, 267", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["988764149"], secondaryAddresses: [] },
  { id: "33", name: "FABIA REGINA LOUREN DA SILVAQ", address: "RUA PADRE MANOEL DA NOBREGA, 171 A", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["988699699"], secondaryAddresses: [] },
  { id: "34", name: "ECLESIANE ALMEIDA DOS SANTOS", address: "RUA DRT ALVARO OZORIO, 200", neighborhood: "PAJUCARA II", city: "NATAL", state: "RN", phone: ["987180249"], secondaryAddresses: [] },
  { id: "35", name: "EMMANUELLY FREITAS", address: "NAN", neighborhood: "PARQUE DAS NAÇOES", city: "NATAL", state: "RN", phone: ["84991960669"], secondaryAddresses: [] },
  { id: "36", name: "CLAUDIO SOARES DO CARMO", address: "AV MARANGUAPE, 970", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["98823-5081"], secondaryAddresses: [] },
  { id: "37", name: "LARYSSA CATIUSSA CORRERIA LIMA", address: "AV. PICO DO CABUGI, 108 .", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["987787921"], secondaryAddresses: [] },
  { id: "38", name: "DIZIA MARINHO CAMARA", address: "AVENIDA DAS FRONTEIRAS, 2535", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["98815-9069"], secondaryAddresses: [] },
  { id: "39", name: "HENRIQUE BILRO CABELEIREIROS LTDA", address: "AVENIDA DAS FRONTEIRAS, 3101 CJ SANTAREM", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["99651972"], secondaryAddresses: [] },
  { id: "40", name: "MEJ CUIDADOS E BELEZA LTDA", address: "AVENIDA DOUTOR JOAO MEDEIROS FILHO,", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["9 8771-0904"], secondaryAddresses: [] },
  { id: "41", name: "JOANA DARC VIEIRA SIMAO", address: "AVENIDA DOUTOR JOAO MEDEIROS FILHO,", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["988377329"], secondaryAddresses: [] },
  { id: "42", name: "INGRID CORCINO BATISTA", address: "AVENIDA GOVERNADOR ANTONIO DE MELO E", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["88931901"], secondaryAddresses: [] },
  { id: "43", name: "DAYANA RUSSIELE MARTINS DA SILVA", address: "AVENIDA GUADALUPE, 2042 B", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["87846797"], secondaryAddresses: [] },
  { id: "44", name: "Renata Thais Araujo dos Santos", address: "AVENIDA ITAPETINGA, 1525 A ITAPETININGA", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["981082600"], secondaryAddresses: [] },
  { id: "45", name: "IARA MENDES DE LIMA 00846626462", address: "AVENIDA ITAPETINGA, 1634 A", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["988111585"], secondaryAddresses: [] },
  { id: "46", name: "KADJA SUERDA DO NASCIMENTO SILVA", address: "AV. DOUTOR JOAO MEDEIROS FILHO, 3895", neighborhood: "REDINHA", city: "NATAL", state: "RN", phone: ["987886452"], secondaryAddresses: [] },
  { id: "47", name: "ELISANDRA MEDEIROS DO NASCIMENTO", address: "AV. JOAO MEDEIROS FILHO, 5421 LOJA 4", neighborhood: "REDINHA", city: "NATAL", state: "RN", phone: ["988588798"], secondaryAddresses: [] },
  { id: "48", name: "FABIANA ADILA", address: "RUA RUA CRISTAIS DE GELO , 41", neighborhood: "REDINHA", city: "NATAL", state: "RN", phone: ["988409590"], secondaryAddresses: [] },
  { id: "49", name: "LARYSSA RAINERY DE LIMA TAVARES", address: "RUA PROFESSOR LEONOR ROCHA , 143 C", neighborhood: "CENTRO", city: "NOVA CRUZ", state: "RN", phone: ["991142530"], secondaryAddresses: [] },
  { id: "50", name: "RAQUEL GOMES DA SILVA AGUIAR", address: "AV AVENIDA BRIGADEIRO EVERALDO BR, 308 .", neighborhood: "BOA", city: "PARNAMIRIM", state: "RN", phone: ["994315244"], secondaryAddresses: [] },
  { id: "51", name: "TAMARA AMORIN", address: "RUA HUBERTO ECO, 185", neighborhood: "BOSQUE DAS COLINAS", city: "PARNAMIRIM", state: "RN", phone: ["849999954716"], secondaryAddresses: [] },
  { id: "52", name: "FÁTIMA CAMARA", address: "RUA CAMPO ALEGRE , 900", neighborhood: "CAJUPIRANGA", city: "PARNAMIRIM", state: "RN", phone: ["988220723"], secondaryAddresses: [] },
  { id: "53", name: "JOSELMA DA SILVA SANTANA TORRESB@", address: "RUA CAMPO BELO, 71", neighborhood: "CAJUPIRANGA", city: "PARNAMIRIM", state: "RN", phone: ["987509710"], secondaryAddresses: [] },
  { id: "54", name: "RAFAELA OLIVEIRA DA SILVA", address: "RUA GILBERTO ROBERTO GOMES, 550", neighborhood: "CAJUPIRANGA", city: "PARNAMIRIM", state: "RN", phone: [], secondaryAddresses: [] },
  { id: "55", name: "IRIS CARLA DE OLIVEIRA PORPINO", address: "RUA MAURILIO BARBOSA DE S, 51 .", neighborhood: "CAJUPIRANGA", city: "PARNAMIRIM", state: "RN", phone: ["994506160"], secondaryAddresses: [] },
  { id: "56", name: "JOELMA DA SILVA BRITO", address: "RUA ROSA MASSUD COSTA , 291", neighborhood: "CAJUPIRANGA", city: "PARNAMIRIM", state: "RN", phone: [], secondaryAddresses: [] },
  { id: "57", name: "LV CABELOS E ESTETICA LTDA", address: "AV BRIGADEIRO EVERALDO BREVES, 204", neighborhood: "CENTRO", city: "PARNAMIRIM", state: "RN", phone: ["32722071"], secondaryAddresses: [] },
  { id: "58", name: "THALVONY SILVA SOUZA 07367765400", address: "RUA ASPIRANTE SANTOS, 95 LJ A", neighborhood: "CENTRO", city: "PARNAMIRIM", state: "RN", phone: ["999551347"], secondaryAddresses: [] },
  { id: "59", name: "JULIANA ANDRADE BRANDAO DE LIMA", address: "RUA EDGAR DANTAS, 34 JC CENTER", neighborhood: "CENTRO", city: "PARNAMIRIM", state: "RN", phone: ["88087285"], secondaryAddresses: [] },
  { id: "60", name: "ANA LUCIA GOMES GUIMARAES", address: "RUA EDGAR DANTAS, 37", neighborhood: "CENTRO", city: "PARNAMIRIM", state: "RN", phone: ["988841970"], secondaryAddresses: [] },
  { id: "61", name: "CENTRO DE BELEZA EBENEZER LTDA", address: "RUA OTAVIO GOMES DE CASTRO, 30 A", neighborhood: "CENTRO", city: "PARNAMIRIM", state: "RN", phone: ["32726038"], secondaryAddresses: [] },
  { id: "62", name: "ALINE FERNANDES COSTA", address: "RUA NOGUEIRA, 94", neighborhood: "CIDADE VERDE", city: "PARNAMIRIM", state: "RN", phone: ["94151933"], secondaryAddresses: [] },
  { id: "63", name: "CINARA", address: "AV. DR ÁTILA PAIVA , 42", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["84 991454404"], secondaryAddresses: [] },
  { id: "64", name: "CLARISSA LOPES TRINDADE TRAJANO", address: "AV. JOAO XXIII, 647", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["84988479958"], secondaryAddresses: [] },
  { id: "65", name: "O LOIRO BEAUTY SALON EIRELI", address: "AVENIDA GOV DIX-SEPT R MAIA , 30", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["3645-4261"], secondaryAddresses: [] },
  { id: "66", name: "ARAINA RAQUEL LOURENCO DA SILVA", address: "RUA BRIGADEIRO PESSOA RAMOS, 69", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["(84) 994384526"], secondaryAddresses: [] },
  { id: "67", name: "DAVISON LUCIANO DA SILVA 09515621429", address: "RUA PROF ELIAH MAIA DO REGO, 58", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["999075061"], secondaryAddresses: [] },
  { id: "68", name: "DAVSON LUCIANO", address: "RUA PROFESOR ELIAH MAIA DO REGO, 11", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["999075061"], secondaryAddresses: [] },
  { id: "69", name: "JÉSSIKA JERÔNIMO", address: "RUA PROFESSOR ELIAH MAIA DO RÊGO, 39", neighborhood: "COHABINAL", city: "PARNAMIRIM", state: "RN", phone: ["994205560"], secondaryAddresses: [] },
  { id: "70", name: "IARA KELLY BEZERRA DE LIMA", address: "AV AEROPORTO BRIGADEIRO EDUARDO GOMES, 201", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["(84) 9865-7720"], secondaryAddresses: [] },
  { id: "71", name: "ERIONETE CUSTODIO DA SILVA", address: "RUA DA SAUDADE , 135", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["988353579"], secondaryAddresses: [] },
  { id: "72", name: "CECILIA STELLA ALVES PEREIRA", address: "RUA AEROP DE PETROLINA, 211", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["996778826"], secondaryAddresses: [] },
  { id: "73", name: "CECILIA STELLA ALVES PEREIRA", address: "RUA AEROPORTO CATARATAS DO IGUACU, 211", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["(84) 9656-3330"], secondaryAddresses: [] },
  { id: "74", name: "ADRIANA JOSEFA DE OLIVEIRA BARBOSA", address: "RUA MONSENHOR WALFREDO GURGEL, 175", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["988969002"], secondaryAddresses: [] },
  { id: "75", name: "VERÔNICA MARIA FELIX", address: "RUA MONSENHOR WALFREDO GURGEL, 175", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["987370030"], secondaryAddresses: [] },
  { id: "76", name: "CELI REJANE DE ARAUJO VIEIRA", address: "RUA RIO GRAJAU, 103 CASA", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["999387401"], secondaryAddresses: [] },
  { id: "78", name: "M S DE MORAIS CARDOSO -", address: "RUA RIO NILO, 22 B", neighborhood: "EMAUS", city: "PARNAMIRIM", state: "RN", phone: ["991784658"], secondaryAddresses: [] },
  { id: "79", name: "ROSY", address: "AV BRIGADERO EDUARDO GOMES, 229", neighborhood: "EMAÚS", city: "PARNAMIRIM", state: "RN", phone: ["988270020"], secondaryAddresses: [] },
  { id: "80", name: "ADRIANA JOSEFA", address: "RUA MONSENHOR WALFREDO GURGEL, 175", neighborhood: "EMAÚS", city: "PARNAMIRIM", state: "RN", phone: ["99936 6877"], secondaryAddresses: [] },
  { id: "81", name: "MARIA MÔNICA TARGINO SILVA", address: "RUA PEDRO NUNES FERREIRA, 412", neighborhood: "MONTE CASTELO", city: "PARNAMIRIM", state: "RN", phone: ["84 997100550"], secondaryAddresses: [] },
  { id: "82", name: "YARA", address: "RUA SADI MENDES, 252", neighborhood: "MONTE CASTELO", city: "PARNAMIRIM", state: "RN", phone: ["988700944"], secondaryAddresses: [] },
  { id: "83", name: "ALTITUDE SALAO DE BELEZA LTDA", address: "AV ABEL CABRAL, 1397 B - LJ 6", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["2040-4040"], secondaryAddresses: [] },
  { id: "84", name: "MERCIO BRUNO STUDIO DE BELEZA LTDA", address: "AV AVENIDA DOS EUCALIPTOS, 67 COMERCIAL", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["991624682"], secondaryAddresses: [] },
  { id: "85", name: "FLAVIA VANESSA DE BRITO FERNANDES", address: "AV MARIA LACERDA MONTENEGRO , 613 SHO", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["996008137"], secondaryAddresses: [] },
  { id: "86", name: "JOSE RENATO PEREIRA DOS SANTOS", address: "AV. ABEL CABRAL, 3012 BL A APTO 103", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["32111838"], secondaryAddresses: [] },
  { id: "87", name: "LUCIANA DE MACEDO ANDRADE", address: "AV. AYRTON SENNA, 0 LOJA 31", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["88997245"], secondaryAddresses: [] },
  { id: "88", name: "MARIA DO CEU DA SILVA MEDEIROS", address: "AV. DOS EUCALIPTOS, 16 LJ 16", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["996084289"], secondaryAddresses: [] },
  { id: "89", name: "ROSIMARY FERREIRA ALVES", address: "AV. PETRA KELLY, 61 CASA 66", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["996225941"], secondaryAddresses: [] },
  { id: "90", name: "CENTRO DE BELEZA BELA LU LTDA", address: "AVENIDA ABEL CABRAL, 4 ESQUINA", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["96197787"], secondaryAddresses: [] },
  { id: "91", name: "DEBORAH RODRIGUES STUDIO DA BELEZA", address: "AVENIDA ABEL CABRAL, 694 LOJA 01", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["88502155"], secondaryAddresses: [] },
  { id: "92", name: "ANA MARIA MARINHO CAVALCANTE", address: "AVENIDA AYRTON SENNA, 1480 1480 SALA 4", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["98873-7580"], secondaryAddresses: [] },
  { id: "93", name: "MONIK ELEM SILVA GOMES", address: "RUA BERNARDO NUNES DE PAULA, 100", neighborhood: "NOVA ESPERANÇA", city: "PARNAMIRIM", state: "RN", phone: ["991562959"], secondaryAddresses: [] },
  { id: "94", name: "CHIRLEIDE LÚCIA", address: "RUA DAS OITICICAS, 1193", neighborhood: "NOVA ESPERANÇA", city: "PARNAMIRIM", state: "RN", phone: ["998304143"], secondaryAddresses: [] },
  { id: "96", name: "LUIZ HENRIQUE PINHEIRO", address: "RUA ROSA FERNANDES DA SILVA, 54", neighborhood: "NOVA ESPERANÇA", city: "PARNAMIRIM", state: "RN", phone: ["84 98759-0734"], secondaryAddresses: [] },
  { id: "97", name: "ANY SPA DAS UNHAS", address: "RUA ROSA FERNANDES DA SILVA, 310", neighborhood: "NOVA ESPERANÇA", city: "PARNAMIRIM", state: "RN", phone: ["84981689072"], secondaryAddresses: [] },
  { id: "98", name: "THAYS OLIVEIRA DA SILVA", address: "RUA SANTA AGATA, 130", neighborhood: "NOVA ESPERANÇA", city: "PARNAMIRIM", state: "RN", phone: ["84998773-1219"], secondaryAddresses: [] },
  { id: "99", name: "HERNANI", address: "AV ÁTILA PAIVA, 42", neighborhood: "PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99172 8882"], secondaryAddresses: [] },
  { id: "100", name: "RIQUELANGELA XAVIER RUFINO", address: "AV ELIZA BRANCO PEREIRA DOS SANTO, 731", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["20208010"], secondaryAddresses: [] },
  { id: "101", name: "PRISCILA SOUZA DE OLIVEIRA", address: "AV OLAVO LACERDA MONTENEGRO, 3801", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["992236006"], secondaryAddresses: [] },
  { id: "102", name: "MARIA EDUARDA SILVA BRAZ", address: "AVENIDA OLAVO LACERDA MONTENEGRO, 4273", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["98622786"], secondaryAddresses: [] },
  { id: "103", name: "TATIANA PIRRO DE PAULA", address: "AVENIDA OLAVO LACERDA MONTENEGRO, 4369", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["99390780"], secondaryAddresses: [] },
  { id: "104", name: "GILZIMERE NOBREGA DE MEDEIROS", address: "RUA FRANCA, 12 A", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["991176517"], secondaryAddresses: [] },
  { id: "105", name: "EMMANUELLY RADYMILA DE FREITAS", address: "RUA GOVERNADOR MARIO COVAS, 22 C", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["91960669"], secondaryAddresses: [] },
  { id: "106", name: "EDSON SALES DO NASCIMENTO", address: "RUA JOSE LIRA DE ANDRADE, 27 SALAO CASA", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["988338214"], secondaryAddresses: [] },
  { id: "107", name: "ANDREA CRISTINA DE OLIVEIRA", address: "RUA LUIZ ALBERTO DANTAS, 2 COPHAB", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["996766683"], secondaryAddresses: [] },
  { id: "108", name: "T PIRRO DE PAULA", address: "AV OLAVO LACERDA MONTENEGRO, SN", neighborhood: "PARQUE DAS ARVORES", city: "PARNAMIRIM", state: "RN", phone: ["(84) 9995-0017"], secondaryAddresses: [] },
  { id: "109", name: "GLICIANNE PEREIRA DA SILVA", address: "AV CASTOR VIEIRA REGIS, 03", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["991756761"], secondaryAddresses: [] },
  { id: "112", name: "MARIA EDUARDA SILVA BRAZ", address: "AV OLAVO LACERDA MONTENEGRO, 4273", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["84 988986809"], secondaryAddresses: [] },
  { id: "113", name: "BARBARA DEBIDEI DA SILVA", address: "AV OLAVO LACERDA MONTENEGRO, 4369", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["84981301264"], secondaryAddresses: [] },
  { id: "114", name: "JORDANA MAYARA FONSECA DE LIMA", address: "RUA LORENA, 293", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["849964684449"], secondaryAddresses: [] },
  { id: "115", name: "ANDREIA CRISTINA DE OLIVEIRA", address: "RUA LUIZ ALBERTO DANTAS, 02", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["84 996306453"], secondaryAddresses: [] },
  { id: "116", name: "MONIQUE CRISTELE DE SANTANA", address: "RUA LUIZ ALBERTO DANTAS, 04 A .", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["8498729 3818"], secondaryAddresses: [] },
  { id: "117", name: "SILVANA DA SILVA SANTOS", address: "RUA SANDOVAL MARTINS DE PAIVA, SN", neighborhood: "PARQUE DAS NAÇÕES", city: "PARNAMIRIM", state: "RN", phone: ["84991515668"], secondaryAddresses: [] },
  { id: "118", name: "ROZILENE BARBOSA DE LIRA 07459311464", address: "RUA DA AURORA, 11", neighborhood: "PARQUE DE EXPOSICOES", city: "PARNAMIRIM", state: "RN", phone: ["(84) 996589363"], secondaryAddresses: [] },
  { id: "119", name: "GEORGE CABELEIREIRO BOSQUES MALL LTDA", address: "ALAMEDA DOS BOSQUES, 990 ANDAR 1", neighborhood: "PARQUE DO JIQUI", city: "PARNAMIRIM", state: "RN", phone: ["98940083"], secondaryAddresses: [] },
  { id: "120", name: "SAMYLA DAYSE", address: "AV MARIA AMELIA, 30", neighborhood: "PARQUE INDUSTRIAL", city: "PARNAMIRIM", state: "RN", phone: ["99855878"], secondaryAddresses: [] },
  { id: "121", name: "MARCELLY DE SOUZA", address: "AV RIO CAJUPIRANGA, 411", neighborhood: "PARQUE INDUSTRIAL", city: "PARNAMIRIM", state: "RN", phone: ["849996321329"], secondaryAddresses: [] },
  { id: "122", name: "ANTONIA MICHELI DA COSTA SILVA", address: "RUA PIRES DE CAMPOS, 70 PONTO", neighborhood: "PASSAGEM DE AREIA", city: "PARNAMIRIM", state: "RN", phone: ["99327724"], secondaryAddresses: [] },
  { id: "123", name: "BILIANE GOMES DA COSTA", address: "RUA LUÍZA MARIA CONCEIÇÃO SANTIAGO, 31A", neighborhood: "PASSAGEM DE AREIA", city: "PARNAMIRIM", state: "RN", phone: ["996092620"], secondaryAddresses: [] },
  { id: "124", name: "GECICLEIDE TEIXEIRA DE LIMA", address: "RUA ELIS REGINA, 758", neighborhood: "PASSGEM DE AREIA", city: "PARNAMIRIM", state: "RN", phone: ["987748903"], secondaryAddresses: [] },
  { id: "125", name: "MADYSON MARCONE DA SILVA BEZERRA", address: "AVENIDA JOAQUIM PATRICIO, 1232 FT AP 15103", neighborhood: "PIUM", city: "PARNAMIRIM", state: "RN", phone: ["987952927"], secondaryAddresses: [] },
  { id: "126", name: "DIANA FERNANDES DOS SANTOS", address: "RUA PADRE CÍCERO, 549", neighborhood: "PIUM", city: "PARNAMIRIM", state: "RN", phone: ["8499664444"], secondaryAddresses: [] },
  { id: "128", name: "ERIVANEIDE ANDRADE DUNGA DO NASCI", address: "RUA OSCARINA MARIA DA CONCEICAO, 110", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["998195581"], secondaryAddresses: [] },
  { id: "129", name: "DANIELLE CARDOSO RODRIGUES", address: "RUA SAO JOAO DA BURRA, 158 PROX AO SUPER RED", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["998494464"], secondaryAddresses: [] },
  { id: "130", name: "DANIELLE CARDOSO RODRIGUES DA SILVA", address: "RUA SAO JOAQUIM, 158 C", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["988386692"], secondaryAddresses: [] },
  { id: "131", name: "RAIZA URBANO", address: "RUA CANDIDO MARTINS DOS SANTOS, 1420", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["987398918"], secondaryAddresses: [] },
  { id: "132", name: "TIÃO SILVA", address: "RUA LUIZA BEZERRA , 78", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["991080182"], secondaryAddresses: [] },
  { id: "133", name: "MAXWELLE CARVALHO _ EXCLUSIVE CABELOS", address: "RUA OSCAR RAMALHO DE FARIAS, 238", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["84988668665"], secondaryAddresses: [] },
  { id: "134", name: "DULCE", address: "RUA RAQUEL GOMES DE CASTRO , 301", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["988039923"], secondaryAddresses: [] },
  { id: "135", name: "DANI CABELOS", address: "RUA SÃO JOAQUIM, 158", neighborhood: "ROSA DOS VENTOS", city: "PARNAMIRIM", state: "RN", phone: ["84998494464"], secondaryAddresses: [] },
  { id: "138", name: "KALINE CARDOZO DA SILVA", address: "AV DOUTOR MÁRIO NEGÓCIO, 1420", neighborhood: "SANTA TEREZA", city: "PARNAMIRIM", state: "RN", phone: ["988676685"], secondaryAddresses: [] },
  { id: "139", name: "OSCAR ITALO DE OLIVEIRA LEMOS", address: "AVENIDA DOUTOR MARIO NEGOCIO, 4100 AP", neighborhood: "SANTA TEREZA", city: "PARNAMIRIM", state: "RN", phone: ["96317626"], secondaryAddresses: [] },
  { id: "140", name: "DEBORA SOUSA", address: "RUA OSCAR RAMALHO DE FARIAS, 251", neighborhood: "SANTA TEREZA", city: "PARNAMIRIM", state: "RN", phone: ["9896684194"], secondaryAddresses: [] },
  { id: "141", name: "D LUCIA", address: "AV. PAULO AFONSO, 2514", neighborhood: "SANTOS REIS", city: "PARNAMIRIM", state: "RN", phone: ["992040382"], secondaryAddresses: [] },
  { id: "142", name: "FRANCISCA REDGENIA DIAS ALVINO", address: "RUA PEDRO BEZERRA FILHO, 6 ANEXO A", neighborhood: "SANTOS REIS", city: "PARNAMIRIM", state: "RN", phone: ["36452303"], secondaryAddresses: [] },
  { id: "143", name: "FRANCISCA REDJENIA DIAS", address: "RUA PEDRO BEZERRA FILHO, 6", neighborhood: "SANTOS REIS", city: "PARNAMIRIM", state: "RN", phone: ["987267790"], secondaryAddresses: [] },
  { id: "144", name: "EDJANE BRITO", address: "RUA PEDRO BEZZERA FILHO, 113", neighborhood: "SANTOS REIS", city: "PARNAMIRIM", state: "RN", phone: ["84994453763"], secondaryAddresses: [] },
  { id: "145", name: "LILIANE DA SILVA MARIANO DANTAS", address: "RUA BERTULINA ANTUNES, 10", neighborhood: "VALE DO SOL", city: "PARNAMIRIM", state: "RN", phone: ["991353758"], secondaryAddresses: [] },
  { id: "146", name: "ANA PAULA DA SILVA BEZERRA ROCHA", address: "RUA CELESTINO POTIGUAR, 210 CASA", neighborhood: "VALE DO SOL", city: "PARNAMIRIM", state: "RN", phone: ["987340298"], secondaryAddresses: [] },
  { id: "147", name: "RITA DE CASSIA COSTA DE SOUZA SILVA", address: "RUA SUB OFICIAL MARCELINO AGOSTINHO COSTA, 50", neighborhood: "VALE DO SOL", city: "PARNAMIRIM", state: "RN", phone: ["(84) 9602-6563"], secondaryAddresses: [] },
  { id: "148", name: "LUZIA", address: "RUA IRENE FERNANDES DE CASTRO, 229", neighborhood: "VALE DO SOL", city: "PARNAMIRIM", state: "RN", phone: [], secondaryAddresses: [] },
  { id: "149", name: "JOSY", address: "AV PERIMETRAL, 347", neighborhood: "VIDA NOVA", city: "PARNAMIRIM", state: "RN", phone: ["999804351"], secondaryAddresses: [] },
  { id: "150", name: "JACICLEIDE JANUARIO NONATO", address: "RUA A. ZUMBI - RIO DO FOGO, S/N CASA", neighborhood: "CENTRO", city: "RIO DO FOGO", state: "RN", phone: ["991153941"], secondaryAddresses: [] },
  { id: "151", name: "FERNANDA DEISE DA SILVA BASTOS - ANÁLISE", address: "RUA CASSITERITA, 1506", neighborhood: "AMARANTE", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["9 8724-0527"], secondaryAddresses: [] },
  { id: "152", name: "DALVINA PEREIRA DE ARAUJO", address: "RUA DA FLORESTA, 520", neighborhood: "AMARANTE", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["994316427"], secondaryAddresses: [] },
  { id: "153", name: "IRLANE LENA DA SILVA PEREIRA", address: "RUA OTAVIO BATISTA DE OLIVEIRA, 13 CONJ", neighborhood: "AMARANTE", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["986272287"], secondaryAddresses: [] },
  { id: "154", name: "MARIA DAS DORES GOMES DA SILVA", address: "RUA VEREADOR ARI TEIXEIRA DANTAS, 21", neighborhood: "CENTRO", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["988478351"], secondaryAddresses: [] },
  { id: "155", name: "CARLA MANUELA QUEIROZ GOMES", address: "RUA CAROLINA, 99 CONJ", neighborhood: "SAO GONCALO DO AMARANTE", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["987317709"], secondaryAddresses: [] },
  { id: "156", name: "RAIMUNDA FERNANDES DE OLIVEIRA", address: "RUA BOA SORTE, 270", neighborhood: "GOLANDIM", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["988872134"], secondaryAddresses: [] },
  { id: "157", name: "RAIMUNDA MARCIA DA SILVA", address: "AVENIDA CIDADE DAS FLORES, 0 LOJA 04", neighborhood: "JARDINS", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["988593697"], secondaryAddresses: [] },
  { id: "158", name: "AMANDA DOS SANTOS ALMEIDA DE OLIVEIRA", address: "AVENIDA CIDADE DAS ROSAS, 131 CASA B", neighborhood: "JARDINS", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["987829632"], secondaryAddresses: [] },
  { id: "159", name: "RIVELLA WEGILLA DA SILVA", address: "RUA FLOR DE RAQUEL, 485 CS 2 - QD 20 - LT 06", neighborhood: "JARDINS", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["988346835"], secondaryAddresses: [] },
  { id: "160", name: "ANDREA CARLA SILVA DE CARVALHO", address: "RUA GENERAL ADJER BARRETO, 476 GOLANDIM", neighborhood: "NOVO", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["987748903"], secondaryAddresses: [] },
  { id: "161", name: "ANIELE MARIA DOMINGOS 05827476439", address: "RUA NOSSA SENHORA CONCEICAO, 165", neighborhood: "NOVO", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["87065594"], secondaryAddresses: [] },
  { id: "162", name: "ALICIANNE LINHARES GOMES ROCHA", address: "RUA JASON ALEX DE N DE ASSIS, 15 RUA 2", neighborhood: "PARQUE DOS IPÊS", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["987234305"], secondaryAddresses: [] },
  { id: "163", name: "ROSANGELA COSTA DO NASCIMENTO", address: "RUA EPITACIO MARINHO DE CARVALHO, 46 CJ", neighborhood: "REGOMOLEIRO", city: "SAO GONCALO DO AMARANTE", state: "RN", phone: ["988426167"], secondaryAddresses: [] },
  { id: "164", name: "JOSE HUMBERTO DOS SANTOS", address: "AV MOIZANIEL CARVALHO, 127 CASA", neighborhood: "CENTRO", city: "SÃO JOSE", state: "RN", phone: ["994338985"], secondaryAddresses: [] },
  { id: "165", name: "F DA S PORFIRIO", address: "AV. MONANZIEL DE CARVALHO, 101", neighborhood: "CENTRO", city: "SÃO JOSE", state: "RN", phone: ["992177809"], secondaryAddresses: [] },
  { id: "166", name: "ANA PATRICIA TEIXEIRA 03674965429", address: "RUA SETE DE SETEMBRO, 124 SALAO", neighborhood: "CENTRO", city: "SÃO JOSE", state: "RN", phone: ["987618402"], secondaryAddresses: [] },
  { id: "167", name: "YURI SILVA BEAUTY CONCEPT LTDA", address: "RUA PREF JUVENAL DE CARVALHO, 51 C", neighborhood: "CENTRO", city: "SÃO JOSE", state: "RN", phone: ["81633864"], secondaryAddresses: [] },
  { id: "168", name: "LAISA MELRY LIMA DA COSTA", address: "AV MACHADO DE ASSIS, 448 BOSQUE DAS", neighborhood: "TABORDA", city: "SÃO JOSE", state: "RN", phone: ["988715420"], secondaryAddresses: [] },
  { id: "169", name: "CALINE TEIXEIRA DA SILVA", address: "RUA DOS DOURADOS, 351", neighborhood: "CENTRO", city: "SAO MIGUEL DO GOSTOSO", state: "RN", phone: ["991954787"], secondaryAddresses: [] },
  { id: "170", name: "JARLENE ROCHA", address: "TRV CORONEL ANTÔNIO BASÍLIO, 121", neighborhood: "SAO JOSE DE MIPIBÚ", city: "SAO JOSE DE MIPIBÚ", state: "RN", phone: ["99118 8022"], secondaryAddresses: [] },
  { id: "171", name: "ROMEICKA RAFAELLE JANUARIO DA SOLIVEIRA", address: "AV BAIA DOS GOLFINHOS , 8831 A", neighborhood: "CENTRO", city: "TIBAU DO SUL", state: "RN", phone: ["991420779"], secondaryAddresses: [] },
  { id: "172", name: "L PAULA DA SILVA", address: "AVENIDA BAIA DOS GOLFINHOS, 965 LOJA 09", neighborhood: "PRAIA DE PIPA", city: "TIBAU DO SUL", state: "RN", phone: ["991034635"], secondaryAddresses: [] },
  { id: "173", name: "SILMARA DA SILVA GONCALVES", address: "RUA RUA DO MIRANTE , 160 SALAO", neighborhood: "PRAIA DE PIPA", city: "TIBAU DO SUL", state: "RN", phone: ["91960694"], secondaryAddresses: [] },
  { id: "174", name: "LAISE LUA DE ANDRADE FURTADO", address: "RUA FRANCISCO JOSE FERREIRA , 33", neighborhood: "CAJUEIRO", city: "TOUROS", state: "RN", phone: ["992057072"], secondaryAddresses: [] },
  { id: "175", name: "MIQUEIAS DE SOUZA TORRES", address: "RUA PREFEITO JOSE AMERICO, 283 CENTRO", neighborhood: "CENTRO", city: "TOUROS", state: "RN", phone: ["994745009"], secondaryAddresses: [] },
  { id: "176", name: "VALDIRA RIBEIRO DA SILVA", address: "RUA SUBURBANA BELA, 109", neighborhood: "CENTRO", city: "TOUROS", state: "RN", phone: ["3263-2518"], secondaryAddresses: [] },
  { id: "177", name: "ADENILSON CARLOS IZAIAS", address: "RUA VER JOAO TEODORO DE SOUZA FILH, 2", neighborhood: "SANTA LUZIA", city: "TOUROS", state: "RN", phone: ["991036964"], secondaryAddresses: [] },
  { id: "178", name: "KARINA DA CRUZ QUIRINO", address: "AV. CEL. DEL PRETO, 90 .", neighborhood: "TOUROS", city: "TOUROS", state: "RN", phone: ["999323132"], secondaryAddresses: [] },
  { id: "179", name: "MIRIAN PEREIRA DA SILVA", address: "RUA PLANICIE DA BORBOREMA, 39", neighborhood: "PAJUCARA", city: "NATAL", state: "RN", phone: ["988916017"], secondaryAddresses: [] },
  { id: "180", name: "KATHIA JUSSARA ALVES DE LIMA", address: "AVENIDA PAULISTANA, 2057", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["988655811"], secondaryAddresses: [] },
  { id: "181", name: "JACIANA MARIA DE GOUVEIA", address: "AVENIDA PAULISTANA, 2057 PANATIS", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["981649976"], secondaryAddresses: [] },
  { id: "182", name: "ROSA ALINE GOMES DA SILVA", address: "RUA ATOL DAS ROCAS, 1073", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["999155659"], secondaryAddresses: [] },
  { id: "183", name: "FLAVIA KELLY TAVARES DOS SANTOS", address: "RUA ENOQUE FONSECA, 2958 GA SANTA", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["987550787"], secondaryAddresses: [] },
  { id: "184", name: "LUCIENE BEZERRA DA SILVA AMORIM", address: "RUA ILHEUS, 2846", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["9 8802-5588"], secondaryAddresses: [] },
  { id: "185", name: "MARIA ELENIR SILVA DE MELO 02546720430", address: "RUA ILHEUS, 2920 VIZINHO AO CARREFOUR", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["36144350"], secondaryAddresses: [] },
  { id: "186", name: "ADRIANA MAURICIO GUERRA DE ANDRADE", address: "RUA ITAPETINGA, 940", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["3322-0345"], secondaryAddresses: [] },
  { id: "187", name: "ELIZABETH LINO PEREIRA 40682315400", address: "RUA ITAPIUNA, 2090 PANATIS", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["988548665"], secondaryAddresses: [] },
  { id: "188", name: "MILANE ALVES DE LIMA", address: "RUA MODELO, 2818 CJ SANTA CATARINA", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["86010097"], secondaryAddresses: [] },
  { id: "189", name: "PRISCILA DA SILVA CARDOSO", address: "RUA PICO DA NEBLINA, 1081", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["9 8720-7937"], secondaryAddresses: [] },
  { id: "190", name: "FLAVIA CALAFANGE TEIXEIRA DE CARVALHO", address: "AVENIDA DEPUTADO GASTAO MARIZ DE FARIA,", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["997075407"], secondaryAddresses: [] },
  { id: "191", name: "FRANCISCA RAIANE DE OLIVEIRA 70769677401", address: "AVENIDA DOS EUCALIPTOS, 02 LJ B,C E D", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["9 9987-1966"], secondaryAddresses: [] },
  { id: "192", name: "MERCIO BRUNO DE ARAUJO", address: "AVENIDA DOS EUCALIPTOS, 067 CS 2", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["9 9162-4682"], secondaryAddresses: [] },
  { id: "193", name: "VALDIRA FELIX DE LIMA PACHECO", address: "AVENIDA DOS EUCALIPTOS, 243 LJ 3 COND SANTA", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99844-7698"], secondaryAddresses: [] },
  { id: "194", name: "FRANCINEIDE LOYOLA DE SOUZA", address: "AVENIDA MADRE TEREZA DE CALCUTA, 31", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["994719266"], secondaryAddresses: [] },
  { id: "195", name: "FRANCINEIDE LOYOLA DE SOUZA 61162140291", address: "AVENIDA MADRE TEREZA DE CALCUTA, 31 LOJA", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["94719266"], secondaryAddresses: [] },
  { id: "196", name: "BELEZA E ESMALTERIA LTDA", address: "AVENIDA MARIA LACERDA MONTENEGRO, 2835", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99039427"], secondaryAddresses: [] },
  { id: "197", name: "AMANDA RAIANE VIEIRA SILVA LTDA", address: "AVENIDA MARIA LACERDA MONTENEGRO 515,", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["81625466"], secondaryAddresses: [] },
  { id: "198", name: "NILVÂNIA DE AZEVEDO GAVÃO MOREIRA", address: "AVENIDA SANTA LUZIA, 1074 CASA 04", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99926-0195"], secondaryAddresses: [] },
  { id: "199", name: "DAIANY JESSICA SANTOS DA SILVA KUPKA", address: "RUA ADEODATO JOSE DOS REIS, 1100 AP 1802", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["91143952"], secondaryAddresses: [] },
  { id: "200", name: "FRANCISCA ALINE NUNES DOS SANTOS", address: "RUA SAO JOAO DA BARRA, 2773 CONJ SANTA", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["88980545"], secondaryAddresses: [] },
  { id: "201", name: "MARIA DAS VITORIA CUNHA OLIVEIRA DA F", address: "RUA TUPI PAULISTA, 74 A", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["988767630"], secondaryAddresses: [] },
  { id: "202", name: "JAILTON SOARES CRUZ", address: "RUA VARZEA ALEGRE, 2694 SALA", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["96308041"], secondaryAddresses: [] },
  { id: "203", name: "LUANA VARELA DA SILVA", address: "RUA VINTE DE AGOSTO, 35 POTENGI", neighborhood: "POTENGI", city: "NATAL", state: "RN", phone: ["987126488"], secondaryAddresses: [] },
  { id: "204", name: "E C DE OLIVEIRA CAMARGO DE DE ROSA", address: "RUA ALGAROBAS, 45", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["987670662"], secondaryAddresses: [] },
  { id: "205", name: "ALISSON PAULINO GOMES DE OLIVEIRA", address: "RUA AMENDOEIRA, 124", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["96843704"], secondaryAddresses: [] },
  { id: "206", name: "GEOVANNA ATALIBA DE OLIVEIRA", address: "RUA ANGICOS, 107 SALAO", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["987610744"], secondaryAddresses: [] },
  { id: "207", name: "REJANE DA S CRISTIANO SALAO DE BELEZA LTDA", address: "RUA ANIBAL BRANDAO, 246 LOJA 03", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["998968468"], secondaryAddresses: [] },
  { id: "208", name: "MARUSK MIKAELLY ALVES DE LIMA", address: "RUA AUGUSTO DOS ANJOS , 46 LJ 02", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99901393"], secondaryAddresses: [] },
  { id: "209", name: "SAYONARA MICHELE DA SILVA", address: "RUA CARMINDO QUADROS, 665 LOJA B", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["994069657"], secondaryAddresses: [] },
  { id: "210", name: "KEANE MOREIRA DA SILVA", address: "RUA CRUZ E SOUZA, 701 SALA 202", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["991907780"], secondaryAddresses: [] },
  { id: "211", name: "CHIRLEIDE LUCIA DA SILVA", address: "RUA DAS OITICICAS, 1193", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["99830-4143"], secondaryAddresses: [] },
  { id: "212", name: "BRENA LADJANE DA SILVA SANTOS", address: "RUA DOS BEM-TE-VIS, 16 QUADRA 4", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["999625758"], secondaryAddresses: [] },
  { id: "213", name: "J OLIVEIRA NETO", address: "RUA ESTUDANTE VALDIR, 169 C", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["92192213"], secondaryAddresses: [] },
  { id: "214", name: "JOAO BATISTA DE MELO", address: "RUA JARDIM DO SERIDO, 48 A CS 09", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["987630694"], secondaryAddresses: [] },
  { id: "215", name: "POLYANNA HONORIO DA SILVA", address: "RUA JOSE NAZARENO PINTO, 64 CD VERDE", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["991674922"], secondaryAddresses: [] },
  { id: "216", name: "PHILLYPE EDUARDO SILVA DE SOUZA", address: "RUA MARIA DOLORES COSTA, 285", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["98334608"], secondaryAddresses: [] },
  { id: "217", name: "VERA CLEIA DE SOUSA SILVA", address: "RUA PRAIA DE TIBAU, 53 B", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["9946622121"], secondaryAddresses: [] },
  { id: "218", name: "LUCICLEIDE MEDEIROS DE SOUZA", address: "RUA PRAIA DE TIBAU, 602 LOJA 03", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["992170337"], secondaryAddresses: [] },
  { id: "219", name: "CRISLAINE CIDRONE FREITAS SANTOS", address: "RUA PRAIA DE TIBAU, 1070 LJ B", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["88187679"], secondaryAddresses: [] },
  { id: "220", name: "LUIZ HENRIQUE GONCALO PINHEIRO", address: "RUA ROSA FERNANDES DA SILVA, 54 C", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["87590734"], secondaryAddresses: [] },
  { id: "221", name: "DANIELI DO NASCIMENTO SILVA", address: "RUA SAO VICENTE, 234 A", neighborhood: "NOVA PARNAMIRIM", city: "PARNAMIRIM", state: "RN", phone: ["994550017"], secondaryAddresses: [] }
];
